# Generated by Django 4.2.9 on 2025-11-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="start date/time"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="end date/time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELED", "Canceled"),
                            ("DONE", "Done"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from client to professional",
                        verbose_name="client notes",
                    ),
                ),
                (
                    "professional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes by professional",
                        verbose_name="professional notes",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ["-start_datetime"],
            },
        ),
    ]
