# Generated by Django 4.2.9 on 2025-11-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="canceled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_canceled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "CLIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="professional",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSIONAL"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_as_professional",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["client", "status"], name="bookings_bo_client__09b1d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["professional", "status"], name="bookings_bo_profess_07771c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["start_datetime"], name="bookings_bo_start_d_d047d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_datetime"],
                name="bookings_bo_status_f6e1f8_idx",
            ),
        ),
    ]
