# Generated by Django 4.2.9 on 2025-11-07 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="professionals",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESSIONAL"},
                related_name="services_offered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
