# Generated by Django 4.2.9 on 2025-11-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeoff",
            name="professional",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSIONAL"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_offs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="professional",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSIONAL"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilityrule",
            unique_together={("professional", "day_of_week", "start_time")},
        ),
    ]
